# Generated by Django 4.0.4 on 2022-04-24 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_product', models.ImageField(blank=True, null=True, upload_to='')),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('product_description', models.TextField(max_length=300, null=True)),
                ('count', models.IntegerField(blank=True, default=0)),
                ('price', models.FloatField(default=1.0)),
                ('url', models.URLField()),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_supplier', models.CharField(max_length=50, unique=True)),
                ('brands', models.CharField(max_length=100)),
                ('supplier_price', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_email', models.EmailField(max_length=254, null=True)),
                ('name', models.CharField(max_length=64, null=True)),
                ('invoice', models.FileField(null=True, upload_to='uploads/%Y/%m/%d/')),
                ('user_uuid', models.UUIDField(editable=False, null=True)),
                ('discount_size', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
